trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      az login --service-principal --username $SP_APP_ID --password $SP_PASSWORD --tenant $SP_TENANT_ID
      # Run your PowerShell script here
