# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/RoundTheCode.AzureTestProject.sln'
  project: '**/RoundTheCode.AzureTestProject.csproj'
steps:
  - task: NuGetToolInstaller@1
    name: 'NuGetToolInstaller'
    displayName: 'NuGet tool installer'

  - task: NuGetCommand@2
    name: 'NuGetRestore'
    displayName: 'NuGet restore packages'
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    name: 'Tests'
    displayName: 'Run tests'
    inputs:
      command: 'test'
      projects: '$(solution)'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    name: 'Publish'
    displayName: 'Publish'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '$(project)'
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: false
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: 'drop'
      path: '$(Build.ArtifactStagingDirectory)'
      downloadPath: '$(Build.ArtifactStagingDirectory)'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: 'dockerfile'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/RoundTheCode.AzureTestProject'
      
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: Docker-Service-Connection
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker-Service-Connection'
      command: 'build'
      Dockerfile: '$(Build.ArtifactStagingDirectory)/RoundTheCode.AzureTestProject/dockerfile'
      tags: 'latest'
      repository: 'Testartifacts'
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker-Service-Connection'
      command: 'push'
      repository: 'Testartifacts'
      tags: 'latest'
  - task: DockerInstaller@0
    displayName: 'Install Docker'
    inputs:
        dockerVersion: '17.09.0-ce'
  - task: Docker@2
    displayName: 'Configure Docker'
    inputs:
      containerRegistry: 'Docker-Service-Connection'

  - task: Docker@2
    inputs:
      containerRegistry: 'Docker-Service-Connection'
      repository: 'Testartifacts'
      command: 'run'
      arguments: '-p 8080:80'
      tags: 'latest'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        response=$(curl http://localhost:8080/api/my)
        if [[ "$response" == "true" ]]; then
          echo "Container test passed" + $response
        else
          echo "Container test failed"
          exit 1
        fi