trigger:
- none
variables:
    - name: servicePrincipalId
      value: 'deeaa022-1358-42fd-9b35-28f5a72f66d0'
    - name: servicePrincipalKey
      value: 'soj8Q~p3-OFiA6pGcpimV6JYo7pTIaeiXjjASagD'
    - name: tenantId
      value: 'f41c0fb4-85fd-4993-b320-77faf9d8d07f'
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureLoginServicePrincipal'
    scriptLocation: 'inlineScript'
    scriptType: bash
    inlineScript: |
      az login --service-principal --username $(servicePrincipalId) --password $(servicePrincipalKey) --tenant $(tenantId)
- task: Bash@3
  displayName: 'Install Terraform'
  inputs:
    targetType: 'inline'
    script: |
      wget https://releases.hashicorp.com/terraform/1.4.5/terraform_1.4.5_linux_amd64.zip
      unzip terraform_1.4.5_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform -version
      echo kartheek
      echo terraform -version
- task: PowerShell@2
  displayName: 'terraform init'
  inputs:
    workingDirectory: $(build.sourcesdirectory)/Terraform
    targetType: 'inline'
    script: |
      terraform login  -input=false
      terraform init 
      terraform plan
