trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3

- script: |
    $myObject = @{
      domain = 'src/CSI.Images.Domain/CSI.Images.Domain.csproj'
      cosmosinfrastructure = 'src/CSI.Images.Infrastructure.Cosmos/CSI.Images.Infrastructure.Cosmos.csproj'
    }
    $myArray = $myObject.GetEnumerator() | ForEach-Object { $_.Value }
    Write-Host "My array is: $myArray"
