trigger:
- none

pool:
  vmImage: 'ubuntu-latest'
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureLoginServicePrincipal'
    scriptLocation: 'inlineScript'
    scriptType: bash
    inlineScript: |
      az login
- task: Bash@3
  displayName: 'Install Terraform'
  inputs:
    targetType: 'inline'
    script: |
      wget https://releases.hashicorp.com/terraform/1.4.5/terraform_1.4.5_linux_amd64.zip
      unzip terraform_1.4.5_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform -version
      echo kartheek
      echo terraform -version
- task: PowerShell@2
  displayName: 'terraform init'
  inputs:
    workingDirectory: $(build.sourcesdirectory)/Terraform
    targetType: 'inline'
    script: |
      terraform init 
      terraform plan
