trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: 'Azure CLI Login'
  inputs:
    azureSubscription: '0886e8f9-5795-44b0-be0f-1b4d34545da6'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login 
