trigger:
- main

pool:
  vmImage: 'windows-latest'
variables:
  - name: azurePassword
    value: "$@!l$2812"
  - name: azureUsername
    value: "kartheek@sailsoftware.com"
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureLoginServicePrincipal'
    scriptLocation: 'inlineScript'
    scriptType: bash
    inlineScript: |
      az login

