trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
variables:
  - name: azurePassword
    value: "$@!l$2812"
  - name: azureUsername
    value: "kartheek@sailsoftware.com"
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureLoginServicePrincipal'
    scriptLocation: 'inlineScript'
    scriptType: bash
    inlineScript: |
      az login
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"

