trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureLoginServicePrincipal'
    scriptLocation: 'inlineScript'
    scriptType: bash
    inlineScript: |
      az login
- task: Bash@3
  displayName: 'Install Terraform'
  inputs:
    targetType: 'inline'
    script: |
      wget https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_amd64.zip
      unzip terraform_1.0.9_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform -version



