trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureLoginServicePrincipal'
    scriptLocation: 'inlineScript'
    scriptType: bash
    inlineScript: |
      az login
