FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
# Install unzip
RUN apt-get update && \
    apt-get install -y unzip
WORKDIR /app

COPY drop.zip /app/

# Unzip the file
RUN unzip drop.zip -d /app/

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "RoundTheCode.AzureTestProject.dll"]