FROM mcr.microsoft.com/windows/nanoserver:1803-amd6
# Install unzip
RUN apt-get update && \
    apt-get install -y unzip
WORKDIR /app

COPY drop.zip /app/

# Unzip the file
RUN unzip drop.zip -d /app/
